In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from sklearn import tree
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [2]:
df=pd.read_csv('hour.csv')

In [3]:
df

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,17375,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,17376,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,17377,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,17378,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,17379,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

In [112]:
df=df.drop(['dteday', 'instant'], axis='columns')

In [113]:
df

,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

# QD Test Model

In [114]:
y=df['casual']
X=df.drop(['casual', 'yr'], axis='columns')

In [115]:
X_train, X_test, y_train, y_test=train_test_split(X, y,test_size= 0.2)

In [121]:
X_test

,season,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,registered,cnt
3397,2,5,11,0,4,1,1,0.74,0.6970,0.66,0.2239,124,160
14487,3,8,20,0,5,1,1,0.80,0.7424,0.49,0.1343,254,356
5639,3,8,10,0,0,0,1,0.70,0.6515,0.61,0.6119,115,142
980,1,2,12,0,0,0,1,0.36,0.3182,0.32,0.4627,94,152
16433,4,11,11,1,4,0,1,0.42,0.4242,0.41,0.0896,143,232
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16857,4,12,4,0,1,1,2,0.38,0.3939,0.94,0.1045,9,12
11862,2,5,11,0,1,1,2,0.56,0.5303,0.83,0.2239,67,79
3680,2,6,6,0,2,1,1,0.60,0.5758,0.78,0.1343,116,126
9854,1,2,14,1,1,0,1,0.32,0.3182,0.36,0.1940,206,263
16605,4,11,16,0,4,1,1,0.36,0.3485,0.40,0.2239,346,370

In [116]:
ct=make_column_transformer((StandardScaler(), X.select_dtypes(include='number').columns),
                           remainder='passthrough')

In [117]:
lr = LinearRegression()

In [118]:
pl=make_pipeline(ct, lr)

In [119]:
pl.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('standardscaler',
                                                  StandardScaler(),
                                                  Index(['season', 'mnth', 'hr', 'holiday', 'weekday', 'workingday',
       'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'registered', 'cnt'],
      dtype='object'))])),
                ('linearregression', LinearRegression())])

In [125]:
pl.predict(X_test.loc[3397:3397, :])

array([36.])

In [126]:
y.loc[3397]

36

In [120]:
cross_val_score(pl, X, y, cv=20).mean()

1.0